package com.cac.components.ui.listener.key;

public enum Key {
    ESC, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, BACK_QUOTE, NUM_1, NUM_2, NUM_3, NUM_4, NUM_5, NUM_6, NUM_7,
    NUM_8, NUM_9, NUM_0, EXCLAMATION_MARK, AT, POUND, DOLLAR, CARET, AMPERSAND, ASTERISK, LEFT_PARENTHESIS,
    RIGHT_PARENTHESIS, UNDERSCORE, PLUS, DASH, EQUALS, BACK_SPACE, TAB, Q, W, E, R, T, Y, U, I, O, P,
    LEFT_SQUARE_BRACKET, RIGHT_SQUARE_BRACKET, LEFT_BRACE, RIGHT_BRACE, BACK_SLASH, A, S, D, F, G, H, J, K, L,
    SEMICOLON, COLON, SINGLE_QUOTE, DOUBLE_QUOTE, ENTER, SHIFT, Z, X, C, V, B, N, M, COMMA, PERIOD, LEFT_ANGLE_BRACKET,
    RIGHT_ANGLE_BRACKET, SLASH, CTRL, ALT, SPACE, UP, DOWN, LEFT, RIGHT, INSERT, DELETE, HOME, END, PAGE_UP, PAGE_DOWN
}
